name: Tests and Code Analysis

on:
  workflow_call:

concurrency:
  group: ci-tests-and-code-analysis-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run automated unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'preview-${{github.actor}}'
    env:
      HEAD: ${{ github.head_ref || github.ref_name }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BUN
        uses: oven-sh/setup-bun@v1

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: 'bun'

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Lint
        run: bun run lint
      # - name: Run tests
      #   run: pnpm test
