name: Production Publishing

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      supabase-working-directory:
        required: true
        type: string
      # vercel-project-id-var:
      #   required: true
      #   type: string
      # subdomain:
      #   required: true
      #   type: string

concurrency:
  group: ci-production-${{ inputs.component }}-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  supabase-prod:
    name: Run migrations and seed data on database
    runs-on: ubuntu-latest
    environment: "production"
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    defaults:
      run:
        working-directory: ${{ inputs.supabase-working-directory }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup Supabase cli
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase preview project
        run: supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}

      - name: Clean database, run migrations and seed data
        run: supabase db push
